# Generated by Django 4.2 on 2024-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('pronouns', models.CharField(max_length=40)),
                ('active_times', models.DateTimeField()),
                ('about', models.CharField(max_length=200)),
                ('discord', models.CharField(max_length=100)),
                ('discord_message_check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
