# Generated by Django 4.2 on 2024-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniventure_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='active_times',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='pronouns',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
