# Generated by Django 4.2 on 2024-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniventure_app', '0002_alter_member_about_alter_member_active_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, height_field=250, upload_to='static/images/user_images', width_field=250),
        ),
    ]
